application: whatasmallworldfb
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.(html|css|js|gif|jpg|png|ico))
  static_files: static/\1
  upload: static/.*
  expiration: "1d"

- url: /.*
  script: main.application
  secure: always

libraries:
- name: django
  version: 1.2

- name: jinja2
  version: latest